build:
  maxIssues: 0
  excludeCorrectable: false
config:
  validation: true
style:
  MagicNumber:
    active: false
  ReturnCount:
    max: 3
  LoopWithTooManyJumpStatements:
    active: false
complexity:
  LongParameterList:
    ignoreAnnotated:
      - Composable
  LongMethod:
    threshold: 70
    ignoreAnnotated:
      - Composable
  TooManyFunctions:
    thresholdInFiles: 15
    thresholdInClasses: 15
  CyclomaticComplexMethod:
    threshold: 20
naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable
exceptions:
  TooGenericExceptionCaught:
    allowedExceptionNameRegex: '_|(ignore|expected).*'
formatting:
  active: true
  android: true
  autoCorrect: true
  Indentation:
    active: false
